-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

use ecommerce_db;

CREATE TABLE category (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	category_name VARCHAR(100) NOT NULL
);
    
CREATE TABLE product (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  product_name VARCHAR(100) NOT NULL,
  price DECIMAL (10,2) NOT NULL,
  stock INT DEFAULT 10 NOT NULL,
  category_id INT,
  FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE tag (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  tag_name VARCHAR(100)
);

CREATE TABLE productTag (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  tag_id INT,
  FOREIGN KEY (tag_id) REFERENCES tag(id)
);
